name: music_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.1
  file_manager: ^1.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  modal_bottom_sheet: ^2.1.2
  lottie: ^1.4.3
  get_storage: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audios/
    - assets/images/
    - assets/lotties/
 
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset:  assets/fonts/Roboto-Thin.ttf
          