name: music_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  audioplayers: ^1.1.1
  file_manager: ^1.0.1
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  modal_bottom_sheet: ^2.1.2
  lottie: ^1.4.3
  get_storage: ^2.0.3
  flutter_bloc: ^8.1.1
  flutter_native_splash: ^2.2.13
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
 
flutter_native_splash:
  image: assets/images/music.png
  color: '#404C6C'

 
          